# Generated by Django 4.2.16 on 2024-11-20 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_mypost_counted_view_mypost_created_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mypost',
            options={'ordering': ['-created_date'], 'verbose_name': 'Any Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AddField(
            model_name='mypost',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
