# Generated by Django 4.2.16 on 2024-11-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_mypost_options_mypost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypost',
            name='image',
            field=models.ImageField(default='blog/default.jpg', upload_to='blog/'),
        ),
    ]
