# Generated by Django 4.2.16 on 2024-11-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='mypost',
            name='login_required',
            field=models.BooleanField(default=False),
        ),
    ]
